name: Compile LaTeX Document
description: Compiles a LaTeX document and checks if the PDF was successfully created.

inputs:
  tex-file:
    description: 'LaTeX filename without the .tex extension'
    required: true
    default: 'document'
  directory:
    description: 'Path to compile the LaTeX file from'
    required: false
    default: '.'

runs:
  using: "composite"
  steps:
    - name: Cache TeX Live
      id: cache-texlive
      uses: actions/cache@v5
      with:
        path: |
          /usr/local/texlive
          ~/.texlive*
        key: ${{ runner.os }}-texlive-v2

    - name: Install LaTeX Dependencies
      if: steps.cache-texlive.outputs.cache-hit != 'true'
      uses: devinatkin/latex-action/install_latex_dependencies@caching-changes

    - name: Compile LaTeX Document
      run: |
        cd "${{ inputs.directory }}"
        latexmk -pdf \
          -interaction=nonstopmode \
          -halt-on-error \
          "${{ inputs.tex-file }}.tex"
      shell: bash

    - name: Check if PDF was created
      run: |
        cd "${{ inputs.directory }}"
        pdf_file="$(basename "${{ inputs.tex-file }}").pdf"

        if [ ! -f "$pdf_file" ]; then
          echo "PDF file was not created"
          exit 1
        fi
      shell: bash