name: Compile LaTeX Document
description: Compiles a LaTeX document and checks if the PDF was successfully created.
inputs:
  tex-file:
    description: 'Path to the LaTeX file to compile'
    required: true
    default: 'document.tex'
  directory: 
    description: 'Path to compile the Latex file from'
    required: false
    default: '.'


runs:
  using: "composite"
  steps:
    - name: Cache Presentations PDFs
      id: cache-paper-pdf
      uses: actions/cache@v4
      with:
        path: ${{ inputs.directory }}
        key: ${{ runner.os }}-presentations-${{ inputs.directory }}-${{ inputs.tex-file }}-${{ hashFiles(format('{0}/**/*.tex', inputs.directory)) }}

    - name: Compile LaTeX Document (Initial Compilation)
      if: steps.cache-paper-pdf.outputs.cache-hit != 'true'
      run: |
        cd ${{ inputs.directory }}
        pdflatex -interaction=nonstopmode ${{ inputs.tex-file }}.tex || true
        biber ${{ inputs.tex-file }} || true
        pdflatex -interaction=nonstopmode ${{ inputs.tex-file }}.tex || true
      shell: bash

    - name: Compile LaTeX Document (Final Compilation)
      if: steps.cache-paper-pdf.outputs.cache-hit != 'true'
      run: |
        cd ${{ inputs.directory }}
        pdflatex -interaction=nonstopmode ${{ inputs.tex-file }}.tex || true
      shell: bash

    - name: Check if PDF was created
      run: |
        cd ${{ inputs.directory }}
        pdf_file=$(basename "${{ inputs.tex-file }}").pdf
        if [ ! -f "$pdf_file" ]; then
          echo "PDF file was not created"
          exit 1
        fi
      shell: bash